### ISSUE TITLE
Error on archivedcases

### ISSUE THREAD

**Issue by nurlix** [Bonitasoft-Community/restapi_context#11]
Hi
according to

-------------------------------- case is archived ? --------------------------------
If the case 9002 is now archived, just continue to ask the case 9002 : the REST API get all the information even if the case is archived. Enjoy a simple way to build the Overview page!

but in my case i get error

7.5.1 Community

http://localhost:8080/bonita/API/bpm/archivedCase?p=0&c=5&f=started_by=204
[  
   {  
      "end_date":"2017-07-07 23:42:44.852",
      "archivedDate":"2017-07-07 23:42:44.852",
      "processDefinitionId":"7801248051032122788"
      "start":"2017-07-07 23:42:23.260",
      "sourceObjectId":"2017",
      "rootCaseId":"2017",
      "id":"6036",
      "state":"completed",
      "started_by":"204",
      "last_update_date":"2017-07-07 23:42:44.852",
      "startedBySubstitute":"204"
   }
]

http://localhost:8080/bonita/API/extension/context?caseId=6036
{
    "context": {
        "caseid": null,
        "isCaseArchived": false,
        "isProcessOverview": false,
        "isAdministrator": true,
        "processdefinitionid": null,
        "isProcessInstanciation": false,
        "userid": 204,
        "isTaskExecution": false,
        "taskid": null,
        "username": "cio"
    }
}

http://localhost:8080/bonita/API/extension/context?caseId=2017
{
    "error": "groovy.lang.MissingMethodException: No signature of method: org.bonitasoft.rest.context.RestContextPilot.searchContextData() is applicable for argument types: (java.lang.Long, org.bonitasoft.engine.bpm.process.impl.internal.ArchivedProcessInstanceImpl, java.lang.Long) values: [6036, org.bonitasoft.engine.bpm.process.impl.internal.ArchivedProcessInstanceImpl@79ff2816[name=Procurement], ...] at groovy.lang.MissingMethodException: No signature of method: org.bonitasoft.rest.context.RestContextPilot.searchContextData() is applicable for argument types: (java.lang.Long, org.bonitasoft.engine.bpm.process.impl.internal.ArchivedProcessInstanceImpl, java.lang.Long) values: [6036, org.bonitasoft.engine.bpm.process.impl.internal.ArchivedProcessInstanceImpl@79ff2816[name=Procurement], ...]\r\n\tat org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)\r\n\tat org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:81)\r\n\tat org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)\r\n\tat org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)\r\n\tat org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)\r\n\tat org.bonitasoft.rest.context.RestContextPilot.decodeParameters(RestContextPilot.groovy:94)\r\n\tat org.bonitasoft.rest.context.RestContextPilot$decodeParameters$0.call(Unknown Source)\r\n\tat org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)\r\n\tat org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)\r\n\tat org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)\r\n\tat org.bonitasoft.rest.context.RestContextHandleGet.doHandle(RestContextHandleGet.groovy:111)\r\n\tat org.bonitasoft.console.common.server.page.RestApiRenderer.doHandle(RestApiRenderer.java:106)\r\n\tat org.bonitasoft.console.common.server.page.RestApiRenderer.renderResponse(RestApiRenderer.java:82)\r\n\tat org.bonitasoft.console.common.server.page.RestApiRenderer.handleRestApiCall(RestApiRenderer.java:63)\r\n\tat org.bonitasoft.web.rest.server.api.extension.ApiExtensionResource.handleRequest(ApiExtensionResource.java:134)\r\n\tat org.bonitasoft.web.rest.server.api.extension.ApiExtensionResource.doHandle(ApiExtensionResource.java:51)\r\n\tat org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:666)\r\n\tat org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:348)\r\n\tat org.restlet.resource.ServerResource.handle(ServerResource.java:1020)\r\n\tat org.restlet.resource.Finder.handle(Finder.java:236)\r\n\tat org.restlet.routing.Filter.doHandle(Filter.java:150)\r\n\tat org.restlet.routing.Filter.handle(Filter.java:197)\r\n\tat org.restlet.routing.Router.doHandle(Router.java:422)\r\n\tat org.restlet.routing.Router.handle(Router.java:641)\r\n\tat org.restlet.routing.Filter.doHandle(Filter.java:150)\r\n\tat org.restlet.routing.Filter.handle(Filter.java:197)\r\n\tat org.restlet.routing.Filter.doHandle(Filter.java:150)\r\n\tat org.restlet.routing.Filter.handle(Filter.java:197)\r\n\tat org.restlet.routing.Filter.doHandle(Filter.java:150)\r\n\tat org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)\r\n\tat org.restlet.routing.Filter.handle(Filter.java:197)\r\n\tat org.restlet.routing.Filter.doHandle(Filter.java:150)\r\n\tat org.restlet.routing.Filter.handle(Filter.java:197)\r\n\tat org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)\r\n\tat org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:77)\r\n\tat org.restlet.Application.handle(Application.java:385)\r\n\tat org.bonitasoft.web.rest.server.BonitaRestletApplication.handle(BonitaRestletApplication.java:179)\r\n\tat org.restlet.routing.Filter.doHandle(Filter.java:150)\r\n\tat org.restlet.routing.Filter.handle(Filter.java:197)\r\n\tat org.restlet.routing.Router.doHandle(Router.java:422)\r\n\tat org.restlet.routing.Router.handle(Router.java:641)\r\n\tat org.restlet.routing.Filter.doHandle(Filter.java:150)\r\n\tat org.restlet.routing.Filter.handle(Filter.java:197)\r\n\tat org.restlet.routing.Router.doHandle(Router.java:422)\r\n\tat org.restlet.routing.Router.handle(Router.java:641)\r\n\tat org.restlet.routing.Filter.doHandle(Filter.java:150)\r\n\tat org.restlet.routing.Filter.handle(Filter.java:197)\r\n\tat org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)\r\n\tat org.restlet.Component.handle(Component.java:408)\r\n\tat org.restlet.Server.handle(Server.java:507)\r\n\tat org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)\r\n\tat org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)\r\n\tat org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:731)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\r\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\r\n\tat org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)\r\n\tat org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)\r\n\tat org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)\r\n\tat org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\r\n\tat org.bonitasoft.console.common.server.login.filter.AbstractAuthorizationFilter.doFilter(AbstractAuthorizationFilter.java:61)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\r\n\tat org.bonitasoft.console.common.server.login.filter.AbstractAuthorizationFilter.doFilter(AbstractAuthorizationFilter.java:61)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\r\n\tat org.bonitasoft.console.common.server.login.filter.NoCacheFilter.doFilter(NoCacheFilter.java:53)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\r\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)\r\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)\r\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)\r\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)\r\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)\r\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)\r\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)\r\n\tat org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)\r\n\tat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)\r\n\tat org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\r\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\n"
}

or am i doing something wrong

**Comment by pierre-yves-monnet** [comment]
Hello,
Sorry about that. This issue was already detected, and should be fixed in the next release (2.9) in preparation.
This new release should be produced soon. I produce this morning  a pre release, could you give me a feedback on please ?

**Comment by nurlix** [comment]
Hi so i tested 2.9

here are results

**For open Case**

    "context": {
        ...
        "caseid": 1004,
        "isCaseArchived": false,
        "caseiduse": 1004,
        "processdefinitionid": 4986305713637096944,
        "isProcessInstanciation": false,
        ...
    }

http://localhost:8080/bonita/API/extension/context?caseId=1004
got correct result except error at the end. Was working perfectly in 2.8

    "error": "Error during exploring the Bdm variable [com.company.model.Procurement_$$_jvstfec_0] : groovy.lang.MissingPropertyException: No such property: RestContextTransformData_18 for class: org.bonitasoft.rest.context.RestContextTransformData;Error during exploring the Bdm variable [com.company.model.Procurement_$$_jvstfec_0] : groovy.lang.MissingPropertyException: No such property: RestContextTransformData_18 for class: org.bonitasoft.rest.context.RestContextTransformData"

**For archived Case**

    "context": {
        ...
        "caseid": 1003,
        "archivedcaseid": 3005,
        "isCaseArchived": true,
        "processdefinitionid": 4986305713637096944,
        "isProcessInstanciation": false,
        ...
    }

http://localhost:8080/bonita/API/extension/context?caseId=1003

got same result as in open case and extra error at the end

    Error during exploring the Bdm variable [com.company.model.Procurement_$$_jvst760_0] : groovy.lang.MissingPropertyException: No such property: RestContextTransformData_18 for class: org.bonitasoft.rest.context.RestContextTransformData"

http://localhost:8080/bonita/API/extension/context?caseId=3005

got only context part

**Comment by pierre-yves-monnet** [comment]
Are you in JDK 1.7 or 1.8 ? 
I will enable by default the 1.8 in the release.

**Comment by nurlix** [comment]
Hi.
seems everything works fine.
oh by the way JDK 1.8
