### ISSUE TITLE
RestApiContext.bos

### ISSUE THREAD

**Issue by etchegaray** [Bonitasoft-Community/restapi_context#14]
I'm sorry but in other issue that is closed, I say that i couldn't open RestApiContext-2.9.2.bos in resources.  I can not import it into Bonita Studio either: **"An error occurred while parsing the BOS archive content. Reason: This BOS archive is not valid"**

I also do not find the link to the .zip file to incorporate it into the resources.

Thanks

Javier Sánchez Etchegaray

**Comment by pierre-yves-monnet** [comment]
Hello ,
a BOS file is not a RESSOURCE.
A RESSOURCE is a Zip file.

You can IMPORT the BOS file in a studio (and I think this bos file is a Subscription File, not a Community)
To import a ressource, load the context.zip file
Hope this help,

I let open the thread 2 or 3 days, please tell us that you can do it,

PS: else, as a Bonitasoft consultant, we can assist you. If you want this kind of service, contact me (pierre-yves.monnet@bonitasoft.com)

Regards,

**Comment by etchegaray** [comment]
Thanks for the reply, but I can not find the link to download 'context.zip'. All links for version 7.5  of the page [rest API extensions ](https://community.bonitasoft.com/project?title=api&field_project_category_tid=All&sort_by=changed&sort_order=DESC) point to  '.bos file'. 
 I have de community version and it  seems those files are a Subscription files.

The first [link ](https://community.bonitasoft.com/project/download/release/25370) that points to a .zip file is version 2.5. Is this the file that I have to download?

Regards

**Comment by etchegaray** [comment]
I try with the link above pointed and it works successfully.
Thank you very much. This API will do my development easier.

**Comment by pierre-yves-monnet** [comment]
Awesome ! Thanks !
