### ISSUE TITLE
Share sources

### ISSUE THREAD

**Issue by KilianStein** [Bonitasoft-Community/restapi_context#2]
Hello,

Is it possible to share sources, tests, pom.xml etc.. of this projets ?

It's easier : 
- to sync this projet with git in dir bonita_home\workspace\processus\restAPIExtensions\restapi_context 
- to realise pull request

Regards,

Kilian

**Comment by pierre-yves-monnet** [comment]
Hello,
I clean the projet, and add the source to SRC.
Attention, to edit it on the studio, you still need to load the BOS file.
