### ISSUE TITLE
Missing artifacts in extension pom

### ISSUE THREAD

**Issue by ecuriotto** [Bonitasoft-Community/restapi_context#3]
I import DemonstrateRestApiContext-2.0.bos
I open ContextAccess project I have 4 Problems  

![image](https://cloud.githubusercontent.com/assets/7021326/15213301/aa8e48d8-1846-11e6-927b-1ddf70ace2c5.png)

thanks

**Comment by pierre-yves-monnet** [comment]
Normally, the REST API EXTENSION are different than the Process.
So, you should import the RestApiExtension separatly.

 I will try to export int he DemonstrateRestApiContext-2.0.bos the REST API
CONTEXT as well.
Thanks to tell me !
And I need to change the path of the BDM...

2016-05-12 4:38 GMT-07:00 ecuriotto notifications@github.com:

> I import DemonstrateRestApiContext-2.0.bos
> I open ContextAccess project I have 4 Problems
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7021326/15213301/aa8e48d8-1846-11e6-927b-1ddf70ace2c5.png
> 
> thanks
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Bonitasoft-Community/restapi_context/issues/3

## 

_Pierre-Yves Monnet_
_Bonitasoft                                Phone +33 (0)6 67 31 68 81_
_Consultant                               Email :
pierre-yves.monnet@bonitasoft.com pierre-yves.monnet@bonitasoft.com_

**Comment by pierre-yves-monnet** [comment]
Hello Enrico,I publish a Demonstrate 2.1 where I export the REST API EXTENSION.
You still need to DEPLOY IT in your local server...

**Comment by ecuriotto** [comment]
Hi Pierre-Yves, the rest api extension was included already in the Demonstrate 2.0, the errors I showed were related to Rest api extension.
They are still there in 2.1, you need to change the pom.xml because it's not aligned to your bdm package: pom=br.com.bonita.ticket, bdm=com.bonita.context .
Then errors disappear and you can deploy the process.
