### ISSUE TITLE
Boolean value don't load from bdm

### ISSUE THREAD

**Issue by KilianStein** [Bonitasoft-Community/restapi_context#4]
Hi,

I notice that my boolean values from the BDM are not load with rest_API on version 7.2.2. Do you have the same issue ?

Regards

Kilian

**Comment by pierre-yves-monnet** [comment]
Hello,
The version 2.2 fixe this issue. 
In fact, in the BDM, the method to access a Boolean has a different name, an the RestContext didn't manage this name...

**Comment by KilianStein** [comment]
It works well thx :) !
